project_id = "zqykoyugubaeealrspxm"

[functions.create-user-account]
verify_jwt = true

[functions.setup-initial-admin]
verify_jwt = false

[functions.create-notification]
verify_jwt = true

[functions.notify-admin-new-reservation]
verify_jwt = true

[functions.chat]
verify_jwt = true

