project_id = "zqykoyugubaeealrspxm"

[functions.notify-flight-delay]
verify_jwt = true

[functions.create-user-account]
verify_jwt = true

[functions.setup-initial-admin]
verify_jwt = false

[functions.create-notification]
verify_jwt = true

[functions.notify-admin-new-reservation]
verify_jwt = true

[functions.chat]
verify_jwt = true

[functions.log-admin-action]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.driver-reminder]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = false

[functions.deduct-agency-balance]
verify_jwt = true

[functions.send-review-request]
verify_jwt = true

[functions.flight-status]
verify_jwt = false

[functions.get-driver-email]
verify_jwt = true

[functions.send-whatsapp]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send-admin]
verify_jwt = true

[functions.customer-portal-auth]
verify_jwt = false

[functions.confirm-booking]
verify_jwt = false

[functions.whatsapp-status]
verify_jwt = true

[functions.whatsapp-delivery-webhook]
verify_jwt = false

[functions.whatsapp-message-status]
verify_jwt = true

[functions.send-quick-booking-price]
verify_jwt = true

[functions.track-visit]
verify_jwt = false
