import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "EN" | "DE" | "FR" | "RU" | "IT" | "ES";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    home: "Home",
    cities: "Cities",
    fleet: "Fleet",
    about: "About",
    contact: "Contact",
    bookNow: "Book Now",
    whatsappBooking: "Reserve on WhatsApp",
    meetGreet: "Meet & Greet Service",
    vipTransfer: "VIP Airport Transfer",
    ourFleet: "Our Fleet",
    destinations: "Destinations",
    reviews: "Reviews",
    priceList: "Price List",
    faq: "FAQ",
    aboutUs: "About Us",
    contactUs: "Contact Us",
    termsConditions: "Terms & Conditions",
    passengers: "Passengers",
    luggage: "Luggage",
    from: "From",
    to: "To",
    price: "Price",
    selectAirport: "Select Airport",
    selectDestination: "Select Destination",
    dateTime: "Date & Time",
    flightNumber: "Flight Number",
    passengerName: "Passenger Name",
    phone: "Phone",
    vehicleType: "Vehicle Type",
    paymentType: "Payment Type",
    sendToWhatsApp: "Send to WhatsApp",
    name: "Name",
    email: "Email",
    message: "Message",
    send: "Send",
    luxuryService: "Luxury Chauffeur Service",
    support247: "24/7 Support",
    flightTracking: "Flight Tracking",
    doorToDoor: "Door-to-Door Service",
    professionalDrivers: "Professional Drivers",
  },
  DE: {
    home: "Startseite",
    cities: "Städte",
    fleet: "Flotte",
    about: "Über uns",
    contact: "Kontakt",
    bookNow: "Jetzt buchen",
    whatsappBooking: "Auf WhatsApp reservieren",
    meetGreet: "Meet & Greet Service",
    vipTransfer: "VIP Flughafentransfer",
    ourFleet: "Unsere Flotte",
    destinations: "Reiseziele",
    reviews: "Bewertungen",
    priceList: "Preisliste",
    faq: "FAQ",
    aboutUs: "Über uns",
    contactUs: "Kontakt",
    termsConditions: "AGB",
    passengers: "Passagiere",
    luggage: "Gepäck",
    from: "Von",
    to: "Nach",
    price: "Preis",
    selectAirport: "Flughafen wählen",
    selectDestination: "Ziel wählen",
    dateTime: "Datum & Uhrzeit",
    flightNumber: "Flugnummer",
    passengerName: "Passagiername",
    phone: "Telefon",
    vehicleType: "Fahrzeugtyp",
    paymentType: "Zahlungsart",
    sendToWhatsApp: "An WhatsApp senden",
    name: "Name",
    email: "E-Mail",
    message: "Nachricht",
    send: "Senden",
    luxuryService: "Luxus-Chauffeurservice",
    support247: "24/7 Support",
    flightTracking: "Flugverfolgung",
    doorToDoor: "Tür-zu-Tür-Service",
    professionalDrivers: "Professionelle Fahrer",
  },
  FR: {
    home: "Accueil",
    cities: "Villes",
    fleet: "Flotte",
    about: "À propos",
    contact: "Contact",
    bookNow: "Réserver",
    whatsappBooking: "Réserver sur WhatsApp",
    meetGreet: "Service Meet & Greet",
    vipTransfer: "Transfert VIP Aéroport",
    ourFleet: "Notre Flotte",
    destinations: "Destinations",
    reviews: "Avis",
    priceList: "Tarifs",
    faq: "FAQ",
    aboutUs: "À propos de nous",
    contactUs: "Contactez-nous",
    termsConditions: "Conditions Générales",
    passengers: "Passagers",
    luggage: "Bagages",
    from: "De",
    to: "À",
    price: "Prix",
    selectAirport: "Sélectionner l'aéroport",
    selectDestination: "Sélectionner la destination",
    dateTime: "Date & Heure",
    flightNumber: "Numéro de vol",
    passengerName: "Nom du passager",
    phone: "Téléphone",
    vehicleType: "Type de véhicule",
    paymentType: "Type de paiement",
    sendToWhatsApp: "Envoyer sur WhatsApp",
    name: "Nom",
    email: "E-mail",
    message: "Message",
    send: "Envoyer",
    luxuryService: "Service de Chauffeur de Luxe",
    support247: "Support 24/7",
    flightTracking: "Suivi de vol",
    doorToDoor: "Service Porte-à-Porte",
    professionalDrivers: "Chauffeurs Professionnels",
  },
  RU: {
    home: "Главная",
    cities: "Города",
    fleet: "Автопарк",
    about: "О нас",
    contact: "Контакты",
    bookNow: "Забронировать",
    whatsappBooking: "Забронировать в WhatsApp",
    meetGreet: "Встреча в аэропорту",
    vipTransfer: "VIP Трансфер из аэропорта",
    ourFleet: "Наш автопарк",
    destinations: "Направления",
    reviews: "Отзывы",
    priceList: "Цены",
    faq: "FAQ",
    aboutUs: "О нас",
    contactUs: "Связаться с нами",
    termsConditions: "Условия",
    passengers: "Пассажиры",
    luggage: "Багаж",
    from: "От",
    to: "До",
    price: "Цена",
    selectAirport: "Выберите аэропорт",
    selectDestination: "Выберите пункт назначения",
    dateTime: "Дата и время",
    flightNumber: "Номер рейса",
    passengerName: "Имя пассажира",
    phone: "Телефон",
    vehicleType: "Тип транспорта",
    paymentType: "Тип оплаты",
    sendToWhatsApp: "Отправить в WhatsApp",
    name: "Имя",
    email: "Email",
    message: "Сообщение",
    send: "Отправить",
    luxuryService: "Люкс трансфер",
    support247: "Поддержка 24/7",
    flightTracking: "Отслеживание рейса",
    doorToDoor: "От двери до двери",
    professionalDrivers: "Профессиональные водители",
  },
  IT: {
    home: "Home",
    cities: "Città",
    fleet: "Flotta",
    about: "Chi siamo",
    contact: "Contatti",
    bookNow: "Prenota ora",
    whatsappBooking: "Prenota su WhatsApp",
    meetGreet: "Servizio Meet & Greet",
    vipTransfer: "Transfer VIP Aeroporto",
    ourFleet: "La nostra flotta",
    destinations: "Destinazioni",
    reviews: "Recensioni",
    priceList: "Listino prezzi",
    faq: "FAQ",
    aboutUs: "Chi siamo",
    contactUs: "Contattaci",
    termsConditions: "Termini e Condizioni",
    passengers: "Passeggeri",
    luggage: "Bagagli",
    from: "Da",
    to: "A",
    price: "Prezzo",
    selectAirport: "Seleziona aeroporto",
    selectDestination: "Seleziona destinazione",
    dateTime: "Data e ora",
    flightNumber: "Numero volo",
    passengerName: "Nome passeggero",
    phone: "Telefono",
    vehicleType: "Tipo veicolo",
    paymentType: "Tipo pagamento",
    sendToWhatsApp: "Invia su WhatsApp",
    name: "Nome",
    email: "Email",
    message: "Messaggio",
    send: "Invia",
    luxuryService: "Servizio Autista di Lusso",
    support247: "Supporto 24/7",
    flightTracking: "Tracciamento volo",
    doorToDoor: "Servizio Porta a Porta",
    professionalDrivers: "Autisti Professionisti",
  },
  ES: {
    home: "Inicio",
    cities: "Ciudades",
    fleet: "Flota",
    about: "Nosotros",
    contact: "Contacto",
    bookNow: "Reservar",
    whatsappBooking: "Reservar en WhatsApp",
    meetGreet: "Servicio Meet & Greet",
    vipTransfer: "Transfer VIP Aeropuerto",
    ourFleet: "Nuestra Flota",
    destinations: "Destinos",
    reviews: "Reseñas",
    priceList: "Lista de precios",
    faq: "FAQ",
    aboutUs: "Sobre nosotros",
    contactUs: "Contáctenos",
    termsConditions: "Términos y Condiciones",
    passengers: "Pasajeros",
    luggage: "Equipaje",
    from: "Desde",
    to: "Hasta",
    price: "Precio",
    selectAirport: "Seleccionar aeropuerto",
    selectDestination: "Seleccionar destino",
    dateTime: "Fecha y hora",
    flightNumber: "Número de vuelo",
    passengerName: "Nombre del pasajero",
    phone: "Teléfono",
    vehicleType: "Tipo de vehículo",
    paymentType: "Tipo de pago",
    sendToWhatsApp: "Enviar a WhatsApp",
    name: "Nombre",
    email: "Correo",
    message: "Mensaje",
    send: "Enviar",
    luxuryService: "Servicio de Chofer de Lujo",
    support247: "Soporte 24/7",
    flightTracking: "Seguimiento de vuelo",
    doorToDoor: "Servicio Puerta a Puerta",
    professionalDrivers: "Conductores Profesionales",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("EN");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
