import React, { createContext, useContext, ReactNode, useEffect } from "react";
import { useLocation } from "react-router-dom";

export type Language = "EN" | "DE" | "FR" | "RU" | "IT" | "ES";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getLocalizedPath: (path: string) => string;
}

const LANGUAGE_PREFIXES: Record<string, Language> = {
  de: "DE",
  fr: "FR",
  ru: "RU",
  it: "IT",
  es: "ES",
};

const LANGUAGE_TO_PREFIX: Record<Language, string> = {
  EN: "",
  DE: "/de",
  FR: "/fr",
  RU: "/ru",
  IT: "/it",
  ES: "/es",
};

const translations: Record<Language, Record<string, string>> = {
  EN: {
    // Navigation
    home: "Home",
    cities: "Cities",
    fleet: "Fleet",
    about: "About",
    contact: "Contact",
    services: "Services",
    login: "Login",
    logout: "Logout",
    myAccount: "My Account",
    bookNow: "Book Now",
    
    // Hero Section
    heroTitle: "Premium Transfer Services",
    heroSubtitle: "Best Airport Transfer Company Experience luxury travel with our professional chauffeur service. Reliable, comfortable, and elegant transportation for every journey.",
    bookYourTransfer: "Book Your Transfer",
    callNow: "Call Now",
    service247: "24/7 Service",
    professionalDrivers: "Professional Drivers",
    luxuryFleet: "Luxury Fleet",
    
    // Features Section
    whyChooseUs: "Why Choose Us",
    experienceTheDifference: "Experience the difference with our premium transfer service",
    safeSecure: "Safe & Secure",
    safeSecureDesc: "Fully licensed, insured vehicles with professional, vetted drivers",
    availability247: "24/7 Availability",
    availability247Desc: "Round-the-clock service for arrivals and departures at any time",
    premiumFleet: "Premium Fleet",
    premiumFleetDesc: "Modern, comfortable vehicles maintained to the highest standards",
    support247: "24/7 Support",
    support247Desc: "Dedicated customer service team available whenever you need us",
    
    // Destinations Section
    topDestinations: "Top Destinations",
    topDestinationsDesc: "Discover our most popular routes with professional drivers and luxury vehicles",
    istanbulHotels: "Istanbul ⇄ Hotels",
    istanbulDesc: "Private VIP airport transfer with professional chauffeur service to all Istanbul hotels.",
    antalyaResorts: "Antalya ⇄ Resort Areas",
    antalyaDesc: "Luxury transfer to Lara, Belek, Kemer, Side and all major resort destinations.",
    bodrumCity: "Bodrum ⇄ City Transfer",
    bodrumDesc: "Premium service to Bodrum Peninsula, Turgutreis, Gümbet and surrounding areas.",
    cappadociaTours: "Cappadocia Tours",
    cappadociaDesc: "Exclusive transfers and tour services throughout the magical Cappadocia region.",
    
    // Services Page
    servicesTitle: "Premium VIP Airport & Chauffeur Services",
    servicesSubtitle: "Luxury transfers across Turkey's top destinations",
    servicesMainTitle: "VIP Airport Transfer Services Across Turkey",
    servicesIntro: "Meet Transfer provides luxury airport transfers, private chauffeur service, and VIP minivan transportation across Turkey's most important airports and holiday destinations. Our fleet includes Mercedes Vito, Mercedes V-Class, VIP Minibuses, and Maybach options. All transfers include professional chauffeurs, flight tracking, meet & greet, bottled water, and 24/7 support.",
    readyToBook: "Ready to Book Your VIP Transfer?",
    contactViaWhatsApp: "Contact us via WhatsApp for instant booking and personalized service. Our team is available 24/7 to assist you.",
    
    // Services List
    istanbulService: "Istanbul Airport Transfer (IST & SAW)",
    istanbulFeature1: "VIP Airport → Hotel Transfers",
    istanbulFeature2: "Taksim, Sultanahmet, Galataport Cruise Port",
    istanbulFeature3: "Business Chauffeur Service",
    istanbulFeature4: "Mercedes Vito & V-Class VIP Minivans",
    istanbulFeature5: "24/7 Service + Flight Tracking + Meet & Greet",
    antalyaService: "Antalya Airport Transfer (AYT)",
    antalyaFeature1: "Lara, Kundu, Belek, Side, Alanya, Kaş, Kemer",
    antalyaFeature2: "Golf Hotel Transfers",
    antalyaFeature3: "Family & Group Minibus Options",
    antalyaFeature4: "Resort & Villa Transfers",
    bodrumService: "Bodrum Airport Transfer (BJV)",
    bodrumFeature1: "Yalıkavak Marina, Türkbükü, Gündoğan, Torba",
    bodrumFeature2: "Luxury Villa & Hotel Transfers",
    bodrumFeature3: "VIP Mercedes Vito, V-Class, and Minibus",
    dalamanService: "Dalaman Airport Transfer (DLM)",
    dalamanFeature1: "Fethiye, Ölüdeniz, Göcek Marina, Marmaris",
    dalamanFeature2: "Yacht Transfers + Villa Transfers",
    dalamanFeature3: "24/7 Private Chauffeur Service",
    izmirService: "Izmir Airport Transfer (ADB)",
    izmirFeature1: "Ephesus, Çeşme, Alaçatı, Kusadasi",
    izmirFeature2: "Hotel, Resort & Cruise Port Transfers",
    cappadociaService: "Cappadocia Airport Transfer (NAV & ASR)",
    cappadociaFeature1: "Göreme, Ürgüp, Avanos, Uçhisar",
    cappadociaFeature2: "Cave Hotels & Balloon Tour Transfers",
    cappadociaFeature3: "VIP private chauffeur for tours",
    
    // About Page
    aboutTitle: "About Meet Transfer",
    aboutSubtitle: "Your Trusted Partner for Premium Airport Transfers",
    whoWeAre: "Who We Are - Turkey's Leading Airport Transfer Service",
    aboutIntro1: "Meet Transfer is Turkey's leading premium airport transfer service, providing luxury transportation across the country's most popular tourist destinations. Founded with a vision to offer travelers a seamless and comfortable journey, we have grown to become the trusted choice for discerning travelers, families, and business executives alike.",
    aboutIntro2: "Our commitment to excellence is reflected in every aspect of our service – from our immaculately maintained Mercedes fleet to our professional, English-speaking drivers who undergo rigorous training. We believe that your journey should be as enjoyable as your destination.",
    yearsExperience: "Years Experience",
    transfersCompleted: "Transfers Completed",
    citiesCovered: "Cities Covered",
    availability: "Availability",
    whyChooseMeetTransfer: "Why Choose Meet Transfer",
    safetyFirst: "Safety First",
    safetyFirstDesc: "All our vehicles are regularly serviced and our drivers are professionally trained.",
    qualityService: "Quality Service",
    qualityServiceDesc: "We pride ourselves on delivering exceptional service with attention to every detail.",
    punctuality: "Punctuality",
    punctualityDesc: "We monitor all flights and ensure your driver is always on time, every time.",
    customerFocus: "Customer Focus",
    customerFocusDesc: "Your comfort and satisfaction are our top priorities throughout your journey.",
    citiesWeServe: "Cities We Serve Across Turkey",
    meetGreetService: "Our VIP Meet & Greet Service",
    meetGreetDesc: "Every airport transfer includes our signature Meet & Greet service. Your driver will be waiting in the arrivals hall with a personalized name board. We monitor your flight in real-time, so even if there are delays, your driver will be there when you land. No waiting, no searching – just a warm welcome and a helping hand with your luggage.",
    ourMission: "Our mission is to provide every guest with a travel experience that exceeds expectations. From the moment you book until you reach your destination, we are committed to your comfort and safety.",
    generalManager: "General Manager",
    readyToExperience: "Ready to Experience the Difference?",
    
    // Contact Page
    contactTitle: "Contact Us",
    contactSubtitle: "We're Here to Help 24/7",
    contactMainTitle: "Contact Meet Transfer - Global Office Locations",
    servingWorldwide: "Serving you from multiple locations worldwide with 24/7 support",
    fastestWay: "Fastest Way to Reach Us",
    instantResponses: "Get instant responses via WhatsApp for your airport transfer booking",
    sendMessage: "Send Us a Message",
    yourName: "Your name",
    howCanWeHelp: "How can we help you?",
    sending: "Sending...",
    messageSent: "Message sent successfully! We will contact you shortly.",
    
    // Fleet Page
    fleetTitle: "Our Luxury Fleet",
    fleetSubtitle: "Premium Mercedes vehicles for every occasion",
    fleetMainTitle: "Mercedes VIP Transfer Fleet",
    fleetIntro: "Our carefully curated fleet of Mercedes vehicles ensures you travel in the utmost comfort and style. From efficient airport transfers to luxury chauffeur service, we have the perfect vehicle for every occasion. All vehicles are regularly maintained and cleaned to the highest standards.",
    needHelp: "Need Help Choosing?",
    contactForHelp: "Contact us and we will help you choose the perfect vehicle for your transfer",
    
    // Vehicles
    vitoVipName: "Mercedes Vito VIP",
    vitoVipDesc: "Our most popular choice for airport transfers. The Mercedes Vito VIP offers spacious seating, ample luggage space, and premium comfort features perfect for families and small groups.",
    vitoName: "Mercedes Vito",
    vitoDesc: "The Mercedes Vito Comfortable family holiday transfer vehicles with best budget.",
    maybachName: "Mercedes Maybach",
    maybachDesc: "The pinnacle of automotive luxury. Our Maybach offers executive rear seating and the smoothest ride for VIP guests and business executives.",
    sprinterName: "Mercedes Sprinter VIP Minibus",
    sprinterDesc: "Perfect for larger groups, our VIP Sprinter offers airline-style seating for up to 16 passengers with individual screens and premium amenities.",
    
    // Destinations Page
    destinationsTitle: "VIP Destinations Across Turkey",
    destinationsSubtitle: "Premium Airport Transfers & Private Chauffeur Services",
    destinationsMainTitle: "Airport Transfer Destinations in Turkey",
    destinationsIntro: "Discover the top destinations we serve across Turkey. From luxury marinas to historic city centers, Meet Transfer provides premium airport transfers, private chauffeurs, and VIP minivan service in every major region.",
    keyLocations: "Key Locations",
    more: "more",
    bookTransfer: "Book",
    transfer: "Transfer",
    premiumVipFleet: "Premium VIP Fleet Available",
    premiumVipFleetDesc: "All destinations feature our luxury Mercedes Vito, V-Class, VIP Minibus, and Maybach vehicles with professional chauffeurs, flight tracking, and 24/7 support.",
    bookViaWhatsApp: "Book via WhatsApp",
    cityAirportTransfers: "City & Airport Transfers",
    resortDestinations: "Resort Destinations",
    luxuryMarinas: "Luxury Marinas",
    coastalAreas: "Coastal Areas",
    aegeanCoast: "Aegean Coast",
    caveHotelsBalloon: "Cave Hotels & Balloon Areas",
    
    // Common
    passengers: "Passengers",
    luggage: "Luggage",
    from: "From",
    to: "To",
    price: "Price",
    name: "Name",
    email: "Email",
    phone: "Phone",
    message: "Message",
    send: "Send",
    whatsappBooking: "Reserve on WhatsApp",
    meetGreet: "Meet & Greet Service",
    vipTransfer: "VIP Airport Transfer",
    ourFleet: "Our Fleet",
    destinations: "Destinations",
    reviews: "Reviews",
    priceList: "Price List",
    faq: "FAQ",
    aboutUs: "About Us",
    contactUs: "Contact Us",
    termsConditions: "Terms & Conditions",
    selectAirport: "Select Airport",
    selectDestination: "Select Destination",
    dateTime: "Date & Time",
    flightNumber: "Flight Number",
    passengerName: "Passenger Name",
    vehicleType: "Vehicle Type",
    paymentType: "Payment Type",
    sendToWhatsApp: "Send to WhatsApp",
    luxuryService: "Luxury Chauffeur Service",
    flightTracking: "Flight Tracking",
    doorToDoor: "Door-to-Door Service",
    learnMore: "Learn More",
  },
  DE: {
    // Navigation
    home: "Startseite",
    cities: "Städte",
    fleet: "Flotte",
    about: "Über uns",
    contact: "Kontakt",
    services: "Dienstleistungen",
    login: "Anmelden",
    logout: "Abmelden",
    myAccount: "Mein Konto",
    bookNow: "Jetzt buchen",
    
    // Hero Section
    heroTitle: "Premium Transfer Services",
    heroSubtitle: "Bestes Flughafentransfer-Unternehmen. Erleben Sie Luxusreisen mit unserem professionellen Chauffeurservice. Zuverlässig, komfortabel und elegant für jede Reise.",
    bookYourTransfer: "Transfer buchen",
    callNow: "Jetzt anrufen",
    service247: "24/7 Service",
    professionalDrivers: "Professionelle Fahrer",
    luxuryFleet: "Luxusflotte",
    
    // Features Section
    whyChooseUs: "Warum uns wählen",
    experienceTheDifference: "Erleben Sie den Unterschied mit unserem Premium-Transferservice",
    safeSecure: "Sicher & Geschützt",
    safeSecureDesc: "Vollständig lizenzierte, versicherte Fahrzeuge mit professionellen, geprüften Fahrern",
    availability247: "24/7 Verfügbarkeit",
    availability247Desc: "Rund-um-die-Uhr-Service für Ankünfte und Abflüge zu jeder Zeit",
    premiumFleet: "Premium Flotte",
    premiumFleetDesc: "Moderne, komfortable Fahrzeuge auf höchstem Standard gewartet",
    support247: "24/7 Support",
    support247Desc: "Engagiertes Kundenservice-Team, das Ihnen jederzeit zur Verfügung steht",
    
    // Destinations Section
    topDestinations: "Top-Reiseziele",
    topDestinationsDesc: "Entdecken Sie unsere beliebtesten Routen mit professionellen Fahrern und Luxusfahrzeugen",
    istanbulHotels: "Istanbul ⇄ Hotels",
    istanbulDesc: "Privater VIP-Flughafentransfer mit professionellem Chauffeurservice zu allen Hotels in Istanbul.",
    antalyaResorts: "Antalya ⇄ Ferienanlagen",
    antalyaDesc: "Luxustransfer nach Lara, Belek, Kemer, Side und allen wichtigen Ferienzielen.",
    bodrumCity: "Bodrum ⇄ Stadttransfer",
    bodrumDesc: "Premium-Service zur Halbinsel Bodrum, Turgutreis, Gümbet und Umgebung.",
    cappadociaTours: "Kappadokien Touren",
    cappadociaDesc: "Exklusive Transfers und Touren in der magischen Region Kappadokien.",
    
    // Services Page
    servicesTitle: "Premium VIP Flughafen- & Chauffeurservices",
    servicesSubtitle: "Luxustransfers zu den Top-Destinationen der Türkei",
    servicesMainTitle: "VIP Flughafentransfer-Services in der Türkei",
    servicesIntro: "Meet Transfer bietet luxuriöse Flughafentransfers, privaten Chauffeurservice und VIP-Minivan-Transport zu den wichtigsten Flughäfen und Urlaubszielen der Türkei. Unsere Flotte umfasst Mercedes Vito, Mercedes V-Klasse, VIP-Minibusse und Maybach-Optionen. Alle Transfers beinhalten professionelle Chauffeure, Flugverfolgung, Meet & Greet, Wasser und 24/7-Support.",
    readyToBook: "Bereit, Ihren VIP-Transfer zu buchen?",
    contactViaWhatsApp: "Kontaktieren Sie uns über WhatsApp für sofortige Buchung und persönlichen Service. Unser Team steht Ihnen 24/7 zur Verfügung.",
    
    // Services List
    istanbulService: "Istanbul Flughafentransfer (IST & SAW)",
    istanbulFeature1: "VIP Flughafen → Hotel Transfers",
    istanbulFeature2: "Taksim, Sultanahmet, Galataport Kreuzfahrthafen",
    istanbulFeature3: "Business Chauffeur Service",
    istanbulFeature4: "Mercedes Vito & V-Klasse VIP Minivans",
    istanbulFeature5: "24/7 Service + Flugverfolgung + Meet & Greet",
    antalyaService: "Antalya Flughafentransfer (AYT)",
    antalyaFeature1: "Lara, Kundu, Belek, Side, Alanya, Kaş, Kemer",
    antalyaFeature2: "Golf-Hotel Transfers",
    antalyaFeature3: "Familien- & Gruppen-Minibus Optionen",
    antalyaFeature4: "Resort- & Villen-Transfers",
    bodrumService: "Bodrum Flughafentransfer (BJV)",
    bodrumFeature1: "Yalıkavak Marina, Türkbükü, Gündoğan, Torba",
    bodrumFeature2: "Luxus-Villa & Hotel Transfers",
    bodrumFeature3: "VIP Mercedes Vito, V-Klasse und Minibus",
    dalamanService: "Dalaman Flughafentransfer (DLM)",
    dalamanFeature1: "Fethiye, Ölüdeniz, Göcek Marina, Marmaris",
    dalamanFeature2: "Yacht-Transfers + Villen-Transfers",
    dalamanFeature3: "24/7 Privater Chauffeurservice",
    izmirService: "Izmir Flughafentransfer (ADB)",
    izmirFeature1: "Ephesus, Çeşme, Alaçatı, Kusadasi",
    izmirFeature2: "Hotel-, Resort- & Kreuzfahrthafen-Transfers",
    cappadociaService: "Kappadokien Flughafentransfer (NAV & ASR)",
    cappadociaFeature1: "Göreme, Ürgüp, Avanos, Uçhisar",
    cappadociaFeature2: "Höhlenhotels & Ballontouren-Transfers",
    cappadociaFeature3: "VIP Privatchauffeur für Touren",
    
    // About Page
    aboutTitle: "Über Meet Transfer",
    aboutSubtitle: "Ihr vertrauenswürdiger Partner für Premium-Flughafentransfers",
    whoWeAre: "Wer wir sind - Türkeis führender Flughafentransfer-Service",
    aboutIntro1: "Meet Transfer ist der führende Premium-Flughafentransfer-Service der Türkei und bietet Luxustransport zu den beliebtesten Touristenzielen des Landes. Gegründet mit der Vision, Reisenden eine nahtlose und komfortable Reise zu bieten, sind wir zur vertrauenswürdigen Wahl für anspruchsvolle Reisende, Familien und Geschäftsführer geworden.",
    aboutIntro2: "Unser Engagement für Exzellenz spiegelt sich in jedem Aspekt unseres Services wider – von unserer makellos gewarteten Mercedes-Flotte bis zu unseren professionellen, englischsprachigen Fahrern, die eine strenge Ausbildung durchlaufen. Wir glauben, dass Ihre Reise genauso angenehm sein sollte wie Ihr Reiseziel.",
    yearsExperience: "Jahre Erfahrung",
    transfersCompleted: "Transfers abgeschlossen",
    citiesCovered: "Abgedeckte Städte",
    availability: "Verfügbarkeit",
    whyChooseMeetTransfer: "Warum Meet Transfer wählen",
    safetyFirst: "Sicherheit zuerst",
    safetyFirstDesc: "Alle unsere Fahrzeuge werden regelmäßig gewartet und unsere Fahrer sind professionell geschult.",
    qualityService: "Qualitätsservice",
    qualityServiceDesc: "Wir sind stolz darauf, außergewöhnlichen Service mit Liebe zum Detail zu bieten.",
    punctuality: "Pünktlichkeit",
    punctualityDesc: "Wir überwachen alle Flüge und stellen sicher, dass Ihr Fahrer immer pünktlich ist.",
    customerFocus: "Kundenorientierung",
    customerFocusDesc: "Ihr Komfort und Ihre Zufriedenheit haben während Ihrer Reise oberste Priorität.",
    citiesWeServe: "Städte, die wir in der Türkei bedienen",
    meetGreetService: "Unser VIP Meet & Greet Service",
    meetGreetDesc: "Jeder Flughafentransfer beinhaltet unseren charakteristischen Meet & Greet Service. Ihr Fahrer wartet in der Ankunftshalle mit einem personalisierten Namensschild. Wir überwachen Ihren Flug in Echtzeit, sodass Ihr Fahrer auch bei Verspätungen da ist, wenn Sie landen. Kein Warten, kein Suchen – nur ein herzlicher Empfang und eine helfende Hand mit Ihrem Gepäck.",
    ourMission: "Unsere Mission ist es, jedem Gast ein Reiseerlebnis zu bieten, das die Erwartungen übertrifft. Vom Moment Ihrer Buchung bis Sie Ihr Ziel erreichen, sind wir Ihrem Komfort und Ihrer Sicherheit verpflichtet.",
    generalManager: "Geschäftsführer",
    readyToExperience: "Bereit, den Unterschied zu erleben?",
    
    // Contact Page
    contactTitle: "Kontaktieren Sie uns",
    contactSubtitle: "Wir sind 24/7 für Sie da",
    contactMainTitle: "Meet Transfer kontaktieren - Globale Standorte",
    servingWorldwide: "Wir bedienen Sie von mehreren Standorten weltweit mit 24/7-Support",
    fastestWay: "Schnellster Weg, uns zu erreichen",
    instantResponses: "Erhalten Sie sofortige Antworten über WhatsApp für Ihre Flughafentransfer-Buchung",
    sendMessage: "Senden Sie uns eine Nachricht",
    yourName: "Ihr Name",
    howCanWeHelp: "Wie können wir Ihnen helfen?",
    sending: "Wird gesendet...",
    messageSent: "Nachricht erfolgreich gesendet! Wir werden Sie in Kürze kontaktieren.",
    
    // Fleet Page
    fleetTitle: "Unsere Luxusflotte",
    fleetSubtitle: "Premium Mercedes-Fahrzeuge für jeden Anlass",
    fleetMainTitle: "Mercedes VIP Transfer Flotte",
    fleetIntro: "Unsere sorgfältig zusammengestellte Mercedes-Flotte garantiert Reisen mit höchstem Komfort und Stil. Von effizienten Flughafentransfers bis zum Luxus-Chauffeurservice haben wir das perfekte Fahrzeug für jeden Anlass. Alle Fahrzeuge werden regelmäßig gewartet und nach höchsten Standards gereinigt.",
    needHelp: "Brauchen Sie Hilfe bei der Auswahl?",
    contactForHelp: "Kontaktieren Sie uns und wir helfen Ihnen, das perfekte Fahrzeug für Ihren Transfer zu wählen",
    
    // Vehicles
    vitoVipName: "Mercedes Vito VIP",
    vitoVipDesc: "Unsere beliebteste Wahl für Flughafentransfers. Der Mercedes Vito VIP bietet geräumige Sitze, viel Gepäckraum und Premium-Komfortfunktionen, perfekt für Familien und kleine Gruppen.",
    vitoName: "Mercedes Vito",
    vitoDesc: "Der Mercedes Vito - komfortable Familienurlaubs-Transferfahrzeuge mit bestem Budget.",
    maybachName: "Mercedes Maybach",
    maybachDesc: "Der Gipfel des automobilen Luxus. Unser Maybach bietet Executive-Rücksitze und die sanfteste Fahrt für VIP-Gäste und Geschäftsführer.",
    sprinterName: "Mercedes Sprinter VIP Minibus",
    sprinterDesc: "Perfekt für größere Gruppen, unser VIP Sprinter bietet Airline-Sitze für bis zu 16 Passagiere mit individuellen Bildschirmen und Premium-Ausstattung.",
    
    // Destinations Page
    destinationsTitle: "VIP-Reiseziele in der Türkei",
    destinationsSubtitle: "Premium Flughafentransfers & Private Chauffeurservices",
    destinationsMainTitle: "Flughafentransfer-Ziele in der Türkei",
    destinationsIntro: "Entdecken Sie die Top-Destinationen, die wir in der Türkei bedienen. Von Luxus-Marinas bis zu historischen Stadtzentren bietet Meet Transfer Premium-Flughafentransfers, private Chauffeure und VIP-Minivan-Service in jeder wichtigen Region.",
    keyLocations: "Wichtige Standorte",
    more: "mehr",
    bookTransfer: "Buchen",
    transfer: "Transfer",
    premiumVipFleet: "Premium VIP Flotte verfügbar",
    premiumVipFleetDesc: "Alle Ziele verfügen über unsere luxuriösen Mercedes Vito, V-Klasse, VIP-Minibus und Maybach-Fahrzeuge mit professionellen Chauffeuren, Flugverfolgung und 24/7-Support.",
    bookViaWhatsApp: "Über WhatsApp buchen",
    cityAirportTransfers: "Stadt- & Flughafentransfers",
    resortDestinations: "Ferienanlagen",
    luxuryMarinas: "Luxus-Marinas",
    coastalAreas: "Küstengebiete",
    aegeanCoast: "Ägäische Küste",
    caveHotelsBalloon: "Höhlenhotels & Ballongebiete",
    
    // Common
    passengers: "Passagiere",
    luggage: "Gepäck",
    from: "Von",
    to: "Nach",
    price: "Preis",
    name: "Name",
    email: "E-Mail",
    phone: "Telefon",
    message: "Nachricht",
    send: "Senden",
    whatsappBooking: "Auf WhatsApp reservieren",
    meetGreet: "Meet & Greet Service",
    vipTransfer: "VIP Flughafentransfer",
    ourFleet: "Unsere Flotte",
    destinations: "Reiseziele",
    reviews: "Bewertungen",
    priceList: "Preisliste",
    faq: "FAQ",
    aboutUs: "Über uns",
    contactUs: "Kontakt",
    termsConditions: "AGB",
    selectAirport: "Flughafen wählen",
    selectDestination: "Ziel wählen",
    dateTime: "Datum & Uhrzeit",
    flightNumber: "Flugnummer",
    passengerName: "Passagiername",
    vehicleType: "Fahrzeugtyp",
    paymentType: "Zahlungsart",
    sendToWhatsApp: "An WhatsApp senden",
    luxuryService: "Luxus-Chauffeurservice",
    flightTracking: "Flugverfolgung",
    doorToDoor: "Tür-zu-Tür-Service",
    learnMore: "Mehr erfahren",
  },
  FR: {
    // Navigation
    home: "Accueil",
    cities: "Villes",
    fleet: "Flotte",
    about: "À propos",
    contact: "Contact",
    services: "Services",
    login: "Connexion",
    logout: "Déconnexion",
    myAccount: "Mon compte",
    bookNow: "Réserver",
    
    // Hero Section
    heroTitle: "Services de Transfert Premium",
    heroSubtitle: "La meilleure société de transfert aéroport. Vivez le voyage de luxe avec notre service de chauffeur professionnel. Transport fiable, confortable et élégant pour chaque trajet.",
    bookYourTransfer: "Réserver votre transfert",
    callNow: "Appeler maintenant",
    service247: "Service 24/7",
    professionalDrivers: "Chauffeurs professionnels",
    luxuryFleet: "Flotte de luxe",
    
    // Features Section
    whyChooseUs: "Pourquoi nous choisir",
    experienceTheDifference: "Découvrez la différence avec notre service de transfert premium",
    safeSecure: "Sûr et sécurisé",
    safeSecureDesc: "Véhicules entièrement autorisés et assurés avec des chauffeurs professionnels vérifiés",
    availability247: "Disponibilité 24/7",
    availability247Desc: "Service 24 heures sur 24 pour les arrivées et départs à tout moment",
    premiumFleet: "Flotte Premium",
    premiumFleetDesc: "Véhicules modernes et confortables entretenus selon les normes les plus élevées",
    support247: "Support 24/7",
    support247Desc: "Équipe de service client dédiée disponible chaque fois que vous en avez besoin",
    
    // Destinations Section
    topDestinations: "Destinations Populaires",
    topDestinationsDesc: "Découvrez nos itinéraires les plus populaires avec des chauffeurs professionnels et des véhicules de luxe",
    istanbulHotels: "Istanbul ⇄ Hôtels",
    istanbulDesc: "Transfert VIP privé depuis l'aéroport avec service de chauffeur professionnel vers tous les hôtels d'Istanbul.",
    antalyaResorts: "Antalya ⇄ Stations balnéaires",
    antalyaDesc: "Transfert de luxe vers Lara, Belek, Kemer, Side et toutes les principales destinations de vacances.",
    bodrumCity: "Bodrum ⇄ Transfert ville",
    bodrumDesc: "Service premium vers la péninsule de Bodrum, Turgutreis, Gümbet et les environs.",
    cappadociaTours: "Tours en Cappadoce",
    cappadociaDesc: "Transferts exclusifs et services de visite dans la région magique de la Cappadoce.",
    
    // Services Page
    servicesTitle: "Services VIP Aéroport & Chauffeur Premium",
    servicesSubtitle: "Transferts de luxe vers les meilleures destinations de Turquie",
    servicesMainTitle: "Services de Transfert VIP Aéroport en Turquie",
    servicesIntro: "Meet Transfer propose des transferts aéroport de luxe, un service de chauffeur privé et un transport VIP en minivan vers les aéroports et destinations de vacances les plus importants de Turquie. Notre flotte comprend Mercedes Vito, Mercedes Classe V, minibus VIP et options Maybach. Tous les transferts incluent chauffeurs professionnels, suivi de vol, accueil personnalisé, eau et support 24/7.",
    readyToBook: "Prêt à réserver votre transfert VIP?",
    contactViaWhatsApp: "Contactez-nous via WhatsApp pour une réservation instantanée et un service personnalisé. Notre équipe est disponible 24/7 pour vous aider.",
    
    // About Page
    aboutTitle: "À propos de Meet Transfer",
    aboutSubtitle: "Votre partenaire de confiance pour les transferts aéroport premium",
    whoWeAre: "Qui nous sommes - Le principal service de transfert aéroport de Turquie",
    aboutIntro1: "Meet Transfer est le principal service de transfert aéroport premium de Turquie, offrant un transport de luxe vers les destinations touristiques les plus populaires du pays. Fondé avec la vision d'offrir aux voyageurs un voyage fluide et confortable, nous sommes devenus le choix de confiance des voyageurs exigeants, des familles et des cadres d'entreprise.",
    aboutIntro2: "Notre engagement envers l'excellence se reflète dans chaque aspect de notre service – de notre flotte Mercedes impeccablement entretenue à nos chauffeurs professionnels anglophones qui suivent une formation rigoureuse. Nous croyons que votre voyage doit être aussi agréable que votre destination.",
    yearsExperience: "Années d'expérience",
    transfersCompleted: "Transferts effectués",
    citiesCovered: "Villes couvertes",
    availability: "Disponibilité",
    whyChooseMeetTransfer: "Pourquoi choisir Meet Transfer",
    safetyFirst: "La sécurité avant tout",
    safetyFirstDesc: "Tous nos véhicules sont régulièrement entretenus et nos chauffeurs sont formés professionnellement.",
    qualityService: "Service de qualité",
    qualityServiceDesc: "Nous sommes fiers de fournir un service exceptionnel avec une attention à chaque détail.",
    punctuality: "Ponctualité",
    punctualityDesc: "Nous surveillons tous les vols et nous assurons que votre chauffeur est toujours à l'heure.",
    customerFocus: "Orientation client",
    customerFocusDesc: "Votre confort et votre satisfaction sont nos priorités absolues tout au long de votre voyage.",
    citiesWeServe: "Villes que nous desservons en Turquie",
    meetGreetService: "Notre service VIP Meet & Greet",
    meetGreetDesc: "Chaque transfert aéroport inclut notre service signature Meet & Greet. Votre chauffeur vous attendra dans le hall des arrivées avec un panneau nominatif personnalisé. Nous surveillons votre vol en temps réel, donc même en cas de retard, votre chauffeur sera là à votre arrivée. Pas d'attente, pas de recherche – juste un accueil chaleureux et une aide avec vos bagages.",
    ourMission: "Notre mission est de fournir à chaque invité une expérience de voyage qui dépasse les attentes. Du moment de votre réservation jusqu'à votre destination, nous nous engageons pour votre confort et votre sécurité.",
    generalManager: "Directeur Général",
    readyToExperience: "Prêt à vivre la différence?",
    
    // Contact Page
    contactTitle: "Contactez-nous",
    contactSubtitle: "Nous sommes là pour vous 24/7",
    contactMainTitle: "Contacter Meet Transfer - Bureaux mondiaux",
    servingWorldwide: "Nous vous servons depuis plusieurs sites dans le monde avec un support 24/7",
    fastestWay: "Le moyen le plus rapide de nous contacter",
    instantResponses: "Obtenez des réponses instantanées via WhatsApp pour votre réservation de transfert aéroport",
    sendMessage: "Envoyez-nous un message",
    yourName: "Votre nom",
    howCanWeHelp: "Comment pouvons-nous vous aider?",
    sending: "Envoi en cours...",
    messageSent: "Message envoyé avec succès! Nous vous contacterons sous peu.",
    
    // Fleet Page
    fleetTitle: "Notre flotte de luxe",
    fleetSubtitle: "Véhicules Mercedes premium pour chaque occasion",
    fleetMainTitle: "Flotte de transfert VIP Mercedes",
    fleetIntro: "Notre flotte Mercedes soigneusement sélectionnée vous garantit de voyager avec le plus grand confort et style. Des transferts aéroport efficaces au service de chauffeur de luxe, nous avons le véhicule parfait pour chaque occasion.",
    needHelp: "Besoin d'aide pour choisir?",
    contactForHelp: "Contactez-nous et nous vous aiderons à choisir le véhicule parfait pour votre transfert",
    
    // Services List
    istanbulService: "Transfert Aéroport Istanbul (IST & SAW)",
    istanbulFeature1: "Transferts VIP Aéroport → Hôtel",
    istanbulFeature2: "Taksim, Sultanahmet, Port de croisière Galataport",
    istanbulFeature3: "Service Chauffeur Business",
    istanbulFeature4: "Mercedes Vito & Minivans VIP Classe V",
    istanbulFeature5: "Service 24/7 + Suivi de vol + Accueil",
    antalyaService: "Transfert Aéroport Antalya (AYT)",
    antalyaFeature1: "Lara, Kundu, Belek, Side, Alanya, Kaş, Kemer",
    antalyaFeature2: "Transferts Hôtels de Golf",
    antalyaFeature3: "Options Minibus Famille & Groupe",
    antalyaFeature4: "Transferts Resort & Villa",
    bodrumService: "Transfert Aéroport Bodrum (BJV)",
    bodrumFeature1: "Yalıkavak Marina, Türkbükü, Gündoğan, Torba",
    bodrumFeature2: "Transferts Villa & Hôtel de Luxe",
    bodrumFeature3: "VIP Mercedes Vito, Classe V et Minibus",
    dalamanService: "Transfert Aéroport Dalaman (DLM)",
    dalamanFeature1: "Fethiye, Ölüdeniz, Göcek Marina, Marmaris",
    dalamanFeature2: "Transferts Yacht + Transferts Villa",
    dalamanFeature3: "Service Chauffeur Privé 24/7",
    izmirService: "Transfert Aéroport Izmir (ADB)",
    izmirFeature1: "Éphèse, Çeşme, Alaçatı, Kusadasi",
    izmirFeature2: "Transferts Hôtel, Resort & Port de croisière",
    cappadociaService: "Transfert Aéroport Cappadoce (NAV & ASR)",
    cappadociaFeature1: "Göreme, Ürgüp, Avanos, Uçhisar",
    cappadociaFeature2: "Hôtels troglodytes & Transferts Tour en Montgolfière",
    cappadociaFeature3: "Chauffeur privé VIP pour tours",
    
    // Vehicles
    vitoVipName: "Mercedes Vito VIP",
    vitoVipDesc: "Notre choix le plus populaire pour les transferts aéroport. Le Mercedes Vito VIP offre des sièges spacieux, un espace bagages généreux et des caractéristiques de confort premium.",
    vitoName: "Mercedes Vito",
    vitoDesc: "Le Mercedes Vito - véhicules de transfert familiaux confortables avec le meilleur budget.",
    maybachName: "Mercedes Maybach",
    maybachDesc: "Le summum du luxe automobile. Notre Maybach offre des sièges arrière executive et le trajet le plus fluide pour les invités VIP.",
    sprinterName: "Mercedes Sprinter VIP Minibus",
    sprinterDesc: "Parfait pour les grands groupes, notre Sprinter VIP offre des sièges style avion pour jusqu'à 16 passagers avec équipements premium.",
    
    // Destinations Page
    destinationsTitle: "Destinations VIP en Turquie",
    destinationsSubtitle: "Transferts Aéroport Premium & Services de Chauffeur Privé",
    destinationsMainTitle: "Destinations de Transfert Aéroport en Turquie",
    destinationsIntro: "Découvrez les meilleures destinations que nous desservons en Turquie. Des marinas de luxe aux centres-villes historiques, Meet Transfer propose des transferts aéroport premium dans chaque région majeure.",
    keyLocations: "Lieux clés",
    more: "plus",
    bookTransfer: "Réserver",
    transfer: "Transfert",
    premiumVipFleet: "Flotte VIP Premium Disponible",
    premiumVipFleetDesc: "Toutes les destinations disposent de nos véhicules Mercedes Vito, Classe V, Minibus VIP et Maybach avec chauffeurs professionnels et support 24/7.",
    bookViaWhatsApp: "Réserver via WhatsApp",
    cityAirportTransfers: "Transferts Ville & Aéroport",
    resortDestinations: "Destinations Resort",
    luxuryMarinas: "Marinas de Luxe",
    coastalAreas: "Zones Côtières",
    aegeanCoast: "Côte Égéenne",
    caveHotelsBalloon: "Hôtels Troglodytes & Zones Montgolfières",
    
    // Common
    passengers: "Passagers",
    luggage: "Bagages",
    from: "De",
    to: "À",
    price: "Prix",
    name: "Nom",
    email: "E-mail",
    phone: "Téléphone",
    message: "Message",
    send: "Envoyer",
    whatsappBooking: "Réserver sur WhatsApp",
    meetGreet: "Service Meet & Greet",
    vipTransfer: "Transfert VIP Aéroport",
    ourFleet: "Notre Flotte",
    destinations: "Destinations",
    reviews: "Avis",
    priceList: "Tarifs",
    faq: "FAQ",
    aboutUs: "À propos de nous",
    contactUs: "Contactez-nous",
    termsConditions: "Conditions Générales",
    selectAirport: "Sélectionner l'aéroport",
    selectDestination: "Sélectionner la destination",
    dateTime: "Date & Heure",
    flightNumber: "Numéro de vol",
    passengerName: "Nom du passager",
    vehicleType: "Type de véhicule",
    paymentType: "Type de paiement",
    sendToWhatsApp: "Envoyer sur WhatsApp",
    luxuryService: "Service de Chauffeur de Luxe",
    flightTracking: "Suivi de vol",
    doorToDoor: "Service Porte-à-Porte",
    learnMore: "En savoir plus",
  },
  RU: {
    // Navigation
    home: "Главная",
    cities: "Города",
    fleet: "Автопарк",
    about: "О нас",
    contact: "Контакты",
    services: "Услуги",
    login: "Вход",
    logout: "Выход",
    myAccount: "Мой аккаунт",
    bookNow: "Забронировать",
    
    // Hero Section
    heroTitle: "Премиум Трансфер Сервис",
    heroSubtitle: "Лучшая компания по трансферу из аэропорта. Испытайте роскошное путешествие с нашим профессиональным сервисом водителя. Надежный, комфортный и элегантный транспорт для каждой поездки.",
    bookYourTransfer: "Забронировать трансфер",
    callNow: "Позвонить сейчас",
    service247: "Сервис 24/7",
    professionalDrivers: "Профессиональные водители",
    luxuryFleet: "Люкс автопарк",
    
    // Features Section
    whyChooseUs: "Почему выбирают нас",
    experienceTheDifference: "Почувствуйте разницу с нашим премиальным трансфер-сервисом",
    safeSecure: "Безопасно и надежно",
    safeSecureDesc: "Полностью лицензированные, застрахованные автомобили с профессиональными, проверенными водителями",
    availability247: "Доступность 24/7",
    availability247Desc: "Круглосуточный сервис для прибытий и отправлений в любое время",
    premiumFleet: "Премиум автопарк",
    premiumFleetDesc: "Современные, комфортные автомобили, обслуживаемые по высшим стандартам",
    support247: "Поддержка 24/7",
    support247Desc: "Выделенная команда службы поддержки, доступная когда вам нужно",
    
    // Destinations Section
    topDestinations: "Популярные направления",
    topDestinationsDesc: "Откройте наши самые популярные маршруты с профессиональными водителями и роскошными автомобилями",
    istanbulHotels: "Стамбул ⇄ Отели",
    istanbulDesc: "Частный VIP трансфер из аэропорта с профессиональным водителем во все отели Стамбула.",
    antalyaResorts: "Анталия ⇄ Курорты",
    antalyaDesc: "Люкс трансфер в Лару, Белек, Кемер, Сиде и все основные курортные направления.",
    bodrumCity: "Бодрум ⇄ Городской трансфер",
    bodrumDesc: "Премиум сервис на полуостров Бодрум, Тургутрейс, Гюмбет и окрестности.",
    cappadociaTours: "Туры в Каппадокию",
    cappadociaDesc: "Эксклюзивные трансферы и экскурсии по волшебному региону Каппадокии.",
    
    // Services Page
    servicesTitle: "Премиум VIP Аэропорт и Услуги Водителя",
    servicesSubtitle: "Люкс трансферы по лучшим направлениям Турции",
    servicesMainTitle: "VIP Трансфер из Аэропорта по Турции",
    servicesIntro: "Meet Transfer предоставляет роскошные трансферы из аэропорта, частный сервис водителя и VIP транспорт на минивэнах по важнейшим аэропортам и курортам Турции. Наш автопарк включает Mercedes Vito, Mercedes V-Class, VIP минибусы и Maybach. Все трансферы включают профессиональных водителей, отслеживание рейса, встречу с табличкой, воду и поддержку 24/7.",
    readyToBook: "Готовы забронировать VIP трансфер?",
    contactViaWhatsApp: "Свяжитесь с нами через WhatsApp для мгновенного бронирования и персонального сервиса. Наша команда доступна 24/7.",
    
    // About Page
    aboutTitle: "О Meet Transfer",
    aboutSubtitle: "Ваш надежный партнер для премиум трансферов из аэропорта",
    whoWeAre: "Кто мы - Ведущий сервис трансфера из аэропорта в Турции",
    aboutIntro1: "Meet Transfer - ведущий премиум сервис трансфера из аэропорта в Турции, предоставляющий люкс транспорт по самым популярным туристическим направлениям страны. Основанный с видением предложить путешественникам беспроблемную и комфортную поездку, мы стали надежным выбором для взыскательных путешественников, семей и бизнес-руководителей.",
    aboutIntro2: "Наша приверженность совершенству отражается в каждом аспекте нашего сервиса – от нашего безупречно обслуживаемого автопарка Mercedes до наших профессиональных англоговорящих водителей, проходящих строгое обучение. Мы верим, что ваше путешествие должно быть таким же приятным, как и ваш пункт назначения.",
    yearsExperience: "Лет опыта",
    transfersCompleted: "Выполненных трансферов",
    citiesCovered: "Охваченных городов",
    availability: "Доступность",
    whyChooseMeetTransfer: "Почему выбирают Meet Transfer",
    safetyFirst: "Безопасность прежде всего",
    safetyFirstDesc: "Все наши автомобили регулярно обслуживаются, а водители профессионально обучены.",
    qualityService: "Качественный сервис",
    qualityServiceDesc: "Мы гордимся предоставлением исключительного сервиса с вниманием к каждой детали.",
    punctuality: "Пунктуальность",
    punctualityDesc: "Мы отслеживаем все рейсы и обеспечиваем, чтобы ваш водитель всегда был вовремя.",
    customerFocus: "Ориентация на клиента",
    customerFocusDesc: "Ваш комфорт и удовлетворение - наши главные приоритеты на протяжении всего путешествия.",
    citiesWeServe: "Города, которые мы обслуживаем в Турции",
    meetGreetService: "Наш VIP Meet & Greet Сервис",
    meetGreetDesc: "Каждый трансфер из аэропорта включает наш фирменный сервис Meet & Greet. Ваш водитель будет ждать в зале прибытия с персональной табличкой. Мы отслеживаем ваш рейс в реальном времени, поэтому даже при задержках ваш водитель будет там, когда вы приземлитесь. Никакого ожидания, никаких поисков – только теплый прием и помощь с багажом.",
    ourMission: "Наша миссия - предоставить каждому гостю путешествие, превосходящее ожидания. С момента бронирования до прибытия в пункт назначения мы привержены вашему комфорту и безопасности.",
    generalManager: "Генеральный директор",
    readyToExperience: "Готовы почувствовать разницу?",
    
    // Contact Page
    contactTitle: "Свяжитесь с нами",
    contactSubtitle: "Мы здесь для вас 24/7",
    contactMainTitle: "Контакты Meet Transfer - Глобальные офисы",
    servingWorldwide: "Обслуживаем вас из нескольких точек по всему миру с поддержкой 24/7",
    fastestWay: "Самый быстрый способ связаться",
    instantResponses: "Получите мгновенные ответы через WhatsApp для бронирования трансфера",
    sendMessage: "Отправьте нам сообщение",
    yourName: "Ваше имя",
    howCanWeHelp: "Как мы можем вам помочь?",
    sending: "Отправка...",
    messageSent: "Сообщение успешно отправлено! Мы свяжемся с вами в ближайшее время.",
    
    // Fleet Page
    fleetTitle: "Наш люкс автопарк",
    fleetSubtitle: "Премиум автомобили Mercedes для любого случая",
    fleetMainTitle: "Автопарк VIP трансферов Mercedes",
    fleetIntro: "Наш тщательно подобранный парк автомобилей Mercedes гарантирует путешествие с максимальным комфортом и стилем. От эффективных трансферов из аэропорта до люкс-сервиса с водителем — у нас есть идеальный автомобиль для любого случая. Все автомобили регулярно обслуживаются и чистятся по высшим стандартам.",
    needHelp: "Нужна помощь с выбором?",
    contactForHelp: "Свяжитесь с нами, и мы поможем выбрать идеальный автомобиль для вашего трансфера",
    
    // Services List
    istanbulService: "Трансфер из аэропорта Стамбула (IST и SAW)",
    istanbulFeature1: "VIP трансфер Аэропорт → Отель",
    istanbulFeature2: "Таксим, Султанахмет, круизный порт Галатапорт",
    istanbulFeature3: "Бизнес-сервис с водителем",
    istanbulFeature4: "Mercedes Vito и V-Class VIP минивэны",
    istanbulFeature5: "Сервис 24/7 + Отслеживание рейса + Встреча",
    antalyaService: "Трансфер из аэропорта Антальи (AYT)",
    antalyaFeature1: "Лара, Кунду, Белек, Сиде, Аланья, Каш, Кемер",
    antalyaFeature2: "Трансферы в гольф-отели",
    antalyaFeature3: "Минибусы для семей и групп",
    antalyaFeature4: "Трансферы в курорты и виллы",
    bodrumService: "Трансфер из аэропорта Бодрума (BJV)",
    bodrumFeature1: "Яликавак Марина, Тюркбюкю, Гюндоган, Торба",
    bodrumFeature2: "Трансферы в люкс виллы и отели",
    bodrumFeature3: "VIP Mercedes Vito, V-Class и минибус",
    dalamanService: "Трансфер из аэропорта Даламана (DLM)",
    dalamanFeature1: "Фетхие, Олюдениз, Марина Гёчек, Мармарис",
    dalamanFeature2: "Трансферы на яхты + Трансферы на виллы",
    dalamanFeature3: "Частный водитель 24/7",
    izmirService: "Трансфер из аэропорта Измира (ADB)",
    izmirFeature1: "Эфес, Чешме, Алачаты, Кушадасы",
    izmirFeature2: "Трансферы в отели, курорты и круизные порты",
    cappadociaService: "Трансфер из аэропорта Каппадокии (NAV и ASR)",
    cappadociaFeature1: "Гёреме, Ургюп, Аванос, Учхисар",
    cappadociaFeature2: "Пещерные отели и туры на воздушных шарах",
    cappadociaFeature3: "VIP частный водитель для туров",
    
    // Vehicles
    vitoVipName: "Mercedes Vito VIP",
    vitoVipDesc: "Наш самый популярный выбор для трансферов из аэропорта. Mercedes Vito VIP предлагает просторные сиденья, много места для багажа и премиальные функции комфорта, идеально подходит для семей и небольших групп.",
    vitoName: "Mercedes Vito",
    vitoDesc: "Mercedes Vito — комфортные семейные автомобили для трансфера с лучшим бюджетом.",
    maybachName: "Mercedes Maybach",
    maybachDesc: "Вершина автомобильной роскоши. Наш Maybach предлагает представительские задние сиденья и самую плавную поездку для VIP-гостей и руководителей.",
    sprinterName: "Mercedes Sprinter VIP Минибус",
    sprinterDesc: "Идеально для больших групп, наш VIP Sprinter предлагает сиденья авиационного класса для до 16 пассажиров с индивидуальными экранами и премиум-удобствами.",
    
    // Destinations Page
    destinationsTitle: "VIP направления по Турции",
    destinationsSubtitle: "Премиум трансферы из аэропорта и частный сервис с водителем",
    destinationsMainTitle: "Направления трансферов из аэропорта в Турции",
    destinationsIntro: "Откройте для себя лучшие направления, которые мы обслуживаем в Турции. От люксовых марин до исторических центров городов, Meet Transfer предоставляет премиум трансферы из аэропорта, частных водителей и VIP минивэн-сервис в каждом крупном регионе.",
    keyLocations: "Ключевые локации",
    more: "ещё",
    bookTransfer: "Забронировать",
    transfer: "Трансфер",
    premiumVipFleet: "Доступен премиум VIP автопарк",
    premiumVipFleetDesc: "Все направления обслуживаются нашими люксовыми автомобилями Mercedes Vito, V-Class, VIP минибус и Maybach с профессиональными водителями, отслеживанием рейсов и поддержкой 24/7.",
    bookViaWhatsApp: "Забронировать через WhatsApp",
    cityAirportTransfers: "Городские и аэропортовые трансферы",
    resortDestinations: "Курортные направления",
    luxuryMarinas: "Люксовые марины",
    coastalAreas: "Прибрежные районы",
    aegeanCoast: "Эгейское побережье",
    caveHotelsBalloon: "Пещерные отели и полёты на шарах",
    
    // Common
    passengers: "Пассажиры",
    luggage: "Багаж",
    from: "От",
    to: "До",
    price: "Цена",
    name: "Имя",
    email: "Email",
    phone: "Телефон",
    message: "Сообщение",
    send: "Отправить",
    whatsappBooking: "Забронировать в WhatsApp",
    meetGreet: "Встреча в аэропорту",
    vipTransfer: "VIP Трансфер из аэропорта",
    ourFleet: "Наш автопарк",
    destinations: "Направления",
    reviews: "Отзывы",
    priceList: "Цены",
    faq: "FAQ",
    aboutUs: "О нас",
    contactUs: "Связаться с нами",
    termsConditions: "Условия",
    selectAirport: "Выберите аэропорт",
    selectDestination: "Выберите пункт назначения",
    dateTime: "Дата и время",
    flightNumber: "Номер рейса",
    passengerName: "Имя пассажира",
    vehicleType: "Тип транспорта",
    paymentType: "Тип оплаты",
    sendToWhatsApp: "Отправить в WhatsApp",
    luxuryService: "Люкс трансфер",
    flightTracking: "Отслеживание рейса",
    doorToDoor: "От двери до двери",
    learnMore: "Узнать больше",
  },
  IT: {
    // Navigation
    home: "Home",
    cities: "Città",
    fleet: "Flotta",
    about: "Chi siamo",
    contact: "Contatti",
    services: "Servizi",
    login: "Accedi",
    logout: "Esci",
    myAccount: "Il mio account",
    bookNow: "Prenota ora",
    
    // Hero Section
    heroTitle: "Servizi di Trasferimento Premium",
    heroSubtitle: "La migliore compagnia di trasferimento aeroportuale. Vivi il viaggio di lusso con il nostro servizio di autista professionale. Trasporto affidabile, confortevole ed elegante per ogni viaggio.",
    bookYourTransfer: "Prenota il tuo trasferimento",
    callNow: "Chiama ora",
    service247: "Servizio 24/7",
    professionalDrivers: "Autisti professionisti",
    luxuryFleet: "Flotta di lusso",
    
    // Features Section
    whyChooseUs: "Perché sceglierci",
    experienceTheDifference: "Scopri la differenza con il nostro servizio di trasferimento premium",
    safeSecure: "Sicuro e protetto",
    safeSecureDesc: "Veicoli completamente autorizzati e assicurati con autisti professionisti verificati",
    availability247: "Disponibilità 24/7",
    availability247Desc: "Servizio 24 ore su 24 per arrivi e partenze in qualsiasi momento",
    premiumFleet: "Flotta Premium",
    premiumFleetDesc: "Veicoli moderni e confortevoli mantenuti ai più alti standard",
    support247: "Supporto 24/7",
    support247Desc: "Team di assistenza clienti dedicato disponibile ogni volta che ne hai bisogno",
    
    // Destinations Section
    topDestinations: "Destinazioni Principali",
    topDestinationsDesc: "Scopri i nostri percorsi più popolari con autisti professionisti e veicoli di lusso",
    istanbulHotels: "Istanbul ⇄ Hotel",
    istanbulDesc: "Trasferimento VIP privato dall'aeroporto con servizio di autista professionale verso tutti gli hotel di Istanbul.",
    antalyaResorts: "Antalya ⇄ Resort",
    antalyaDesc: "Trasferimento di lusso verso Lara, Belek, Kemer, Side e tutte le principali destinazioni turistiche.",
    bodrumCity: "Bodrum ⇄ Trasferimento città",
    bodrumDesc: "Servizio premium per la penisola di Bodrum, Turgutreis, Gümbet e dintorni.",
    cappadociaTours: "Tour della Cappadocia",
    cappadociaDesc: "Trasferimenti esclusivi e servizi di tour nella magica regione della Cappadocia.",
    
    // Services Page
    servicesTitle: "Servizi VIP Aeroporto e Autista Premium",
    servicesSubtitle: "Trasferimenti di lusso nelle migliori destinazioni della Turchia",
    servicesMainTitle: "Servizi di Trasferimento VIP Aeroporto in Turchia",
    servicesIntro: "Meet Transfer offre trasferimenti aeroportuali di lusso, servizio di autista privato e trasporto VIP in minivan verso gli aeroporti e le destinazioni turistiche più importanti della Turchia. La nostra flotta include Mercedes Vito, Mercedes Classe V, minibus VIP e opzioni Maybach. Tutti i trasferimenti includono autisti professionisti, tracciamento voli, accoglienza personalizzata, acqua e supporto 24/7.",
    readyToBook: "Pronto a prenotare il tuo trasferimento VIP?",
    contactViaWhatsApp: "Contattaci via WhatsApp per prenotazione istantanea e servizio personalizzato. Il nostro team è disponibile 24/7 per assisterti.",
    
    // About Page
    aboutTitle: "Chi è Meet Transfer",
    aboutSubtitle: "Il tuo partner di fiducia per trasferimenti aeroportuali premium",
    whoWeAre: "Chi siamo - Il principale servizio di trasferimento aeroportuale della Turchia",
    aboutIntro1: "Meet Transfer è il principale servizio di trasferimento aeroportuale premium della Turchia, che offre trasporto di lusso verso le destinazioni turistiche più popolari del paese. Fondato con la visione di offrire ai viaggiatori un viaggio senza problemi e confortevole, siamo diventati la scelta di fiducia per viaggiatori esigenti, famiglie e dirigenti aziendali.",
    aboutIntro2: "Il nostro impegno per l'eccellenza si riflette in ogni aspetto del nostro servizio - dalla nostra flotta Mercedes perfettamente mantenuta ai nostri autisti professionisti anglofoni che seguono una formazione rigorosa. Crediamo che il tuo viaggio debba essere piacevole quanto la tua destinazione.",
    yearsExperience: "Anni di esperienza",
    transfersCompleted: "Trasferimenti completati",
    citiesCovered: "Città coperte",
    availability: "Disponibilità",
    whyChooseMeetTransfer: "Perché scegliere Meet Transfer",
    safetyFirst: "Sicurezza prima di tutto",
    safetyFirstDesc: "Tutti i nostri veicoli sono regolarmente revisionati e i nostri autisti sono formati professionalmente.",
    qualityService: "Servizio di qualità",
    qualityServiceDesc: "Siamo orgogliosi di fornire un servizio eccezionale con attenzione a ogni dettaglio.",
    punctuality: "Puntualità",
    punctualityDesc: "Monitoriamo tutti i voli e assicuriamo che il tuo autista sia sempre puntuale.",
    customerFocus: "Focus sul cliente",
    customerFocusDesc: "Il tuo comfort e la tua soddisfazione sono le nostre priorità assolute durante il viaggio.",
    citiesWeServe: "Città che serviamo in Turchia",
    meetGreetService: "Il nostro servizio VIP Meet & Greet",
    meetGreetDesc: "Ogni trasferimento aeroportuale include il nostro servizio firma Meet & Greet. Il tuo autista ti aspetterà nella hall arrivi con un cartello personalizzato. Monitoriamo il tuo volo in tempo reale, quindi anche in caso di ritardi, il tuo autista sarà lì quando atterri. Nessuna attesa, nessuna ricerca - solo un caloroso benvenuto e una mano con i bagagli.",
    ourMission: "La nostra missione è fornire a ogni ospite un'esperienza di viaggio che superi le aspettative. Dal momento della prenotazione fino all'arrivo a destinazione, siamo impegnati per il tuo comfort e la tua sicurezza.",
    generalManager: "Direttore Generale",
    readyToExperience: "Pronto a vivere la differenza?",
    
    // Contact Page
    contactTitle: "Contattaci",
    contactSubtitle: "Siamo qui per te 24/7",
    contactMainTitle: "Contatta Meet Transfer - Sedi globali",
    servingWorldwide: "Ti serviamo da più sedi in tutto il mondo con supporto 24/7",
    fastestWay: "Il modo più veloce per contattarci",
    instantResponses: "Ricevi risposte istantanee via WhatsApp per la tua prenotazione di trasferimento",
    sendMessage: "Inviaci un messaggio",
    yourName: "Il tuo nome",
    howCanWeHelp: "Come possiamo aiutarti?",
    sending: "Invio in corso...",
    messageSent: "Messaggio inviato con successo! Ti contatteremo a breve.",
    
    // Fleet Page
    fleetTitle: "La nostra flotta di lusso",
    fleetSubtitle: "Veicoli Mercedes premium per ogni occasione",
    fleetMainTitle: "Flotta di trasferimento VIP Mercedes",
    fleetIntro: "La nostra flotta Mercedes accuratamente selezionata garantisce viaggi con il massimo comfort e stile. Dai trasferimenti aeroportuali efficienti al servizio di autista di lusso, abbiamo il veicolo perfetto per ogni occasione. Tutti i veicoli sono regolarmente revisionati e puliti secondo i più alti standard.",
    needHelp: "Hai bisogno di aiuto per scegliere?",
    contactForHelp: "Contattaci e ti aiuteremo a scegliere il veicolo perfetto per il tuo trasferimento",
    
    // Services List
    istanbulService: "Trasferimento Aeroporto Istanbul (IST & SAW)",
    istanbulFeature1: "Trasferimenti VIP Aeroporto → Hotel",
    istanbulFeature2: "Taksim, Sultanahmet, Porto crociere Galataport",
    istanbulFeature3: "Servizio Autista Business",
    istanbulFeature4: "Mercedes Vito & Minivan VIP Classe V",
    istanbulFeature5: "Servizio 24/7 + Tracciamento volo + Accoglienza",
    antalyaService: "Trasferimento Aeroporto Antalya (AYT)",
    antalyaFeature1: "Lara, Kundu, Belek, Side, Alanya, Kaş, Kemer",
    antalyaFeature2: "Trasferimenti Hotel Golf",
    antalyaFeature3: "Opzioni Minibus Famiglia & Gruppo",
    antalyaFeature4: "Trasferimenti Resort & Villa",
    bodrumService: "Trasferimento Aeroporto Bodrum (BJV)",
    bodrumFeature1: "Yalıkavak Marina, Türkbükü, Gündoğan, Torba",
    bodrumFeature2: "Trasferimenti Villa & Hotel di Lusso",
    bodrumFeature3: "VIP Mercedes Vito, Classe V e Minibus",
    dalamanService: "Trasferimento Aeroporto Dalaman (DLM)",
    dalamanFeature1: "Fethiye, Ölüdeniz, Göcek Marina, Marmaris",
    dalamanFeature2: "Trasferimenti Yacht + Trasferimenti Villa",
    dalamanFeature3: "Servizio Autista Privato 24/7",
    izmirService: "Trasferimento Aeroporto Izmir (ADB)",
    izmirFeature1: "Efeso, Çeşme, Alaçatı, Kusadasi",
    izmirFeature2: "Trasferimenti Hotel, Resort & Porto crociere",
    cappadociaService: "Trasferimento Aeroporto Cappadocia (NAV & ASR)",
    cappadociaFeature1: "Göreme, Ürgüp, Avanos, Uçhisar",
    cappadociaFeature2: "Hotel rupestri & Trasferimenti Tour Mongolfiera",
    cappadociaFeature3: "Autista privato VIP per tour",
    
    // Vehicles
    vitoVipName: "Mercedes Vito VIP",
    vitoVipDesc: "La nostra scelta più popolare per i trasferimenti aeroportuali. Il Mercedes Vito VIP offre sedili spaziosi, ampio spazio bagagli e caratteristiche di comfort premium, perfetto per famiglie e piccoli gruppi.",
    vitoName: "Mercedes Vito",
    vitoDesc: "Il Mercedes Vito - veicoli di trasferimento familiari confortevoli con il miglior budget.",
    maybachName: "Mercedes Maybach",
    maybachDesc: "L'apice del lusso automobilistico. Il nostro Maybach offre sedili posteriori executive e il viaggio più fluido per ospiti VIP e dirigenti.",
    sprinterName: "Mercedes Sprinter VIP Minibus",
    sprinterDesc: "Perfetto per gruppi più grandi, il nostro Sprinter VIP offre sedili stile aereo per fino a 16 passeggeri con schermi individuali e comfort premium.",
    
    // Destinations Page
    destinationsTitle: "Destinazioni VIP in Turchia",
    destinationsSubtitle: "Trasferimenti Aeroporto Premium & Servizi di Autista Privato",
    destinationsMainTitle: "Destinazioni di Trasferimento Aeroporto in Turchia",
    destinationsIntro: "Scopri le migliori destinazioni che serviamo in Turchia. Dalle marine di lusso ai centri storici, Meet Transfer offre trasferimenti aeroportuali premium, autisti privati e servizio VIP minivan in ogni regione principale.",
    keyLocations: "Località chiave",
    more: "altro",
    bookTransfer: "Prenota",
    transfer: "Trasferimento",
    premiumVipFleet: "Flotta VIP Premium Disponibile",
    premiumVipFleetDesc: "Tutte le destinazioni dispongono dei nostri veicoli Mercedes Vito, Classe V, Minibus VIP e Maybach di lusso con autisti professionisti, tracciamento voli e supporto 24/7.",
    bookViaWhatsApp: "Prenota via WhatsApp",
    cityAirportTransfers: "Trasferimenti Città & Aeroporto",
    resortDestinations: "Destinazioni Resort",
    luxuryMarinas: "Marine di Lusso",
    coastalAreas: "Zone Costiere",
    aegeanCoast: "Costa Egea",
    caveHotelsBalloon: "Hotel Rupestri & Zone Mongolfiere",
    
    // Common
    passengers: "Passeggeri",
    luggage: "Bagagli",
    from: "Da",
    to: "A",
    price: "Prezzo",
    name: "Nome",
    email: "Email",
    phone: "Telefono",
    message: "Messaggio",
    send: "Invia",
    whatsappBooking: "Prenota su WhatsApp",
    meetGreet: "Servizio Meet & Greet",
    vipTransfer: "Trasferimento VIP Aeroporto",
    ourFleet: "La nostra flotta",
    destinations: "Destinazioni",
    reviews: "Recensioni",
    priceList: "Listino prezzi",
    faq: "FAQ",
    aboutUs: "Chi siamo",
    contactUs: "Contattaci",
    termsConditions: "Termini e Condizioni",
    selectAirport: "Seleziona aeroporto",
    selectDestination: "Seleziona destinazione",
    dateTime: "Data e ora",
    flightNumber: "Numero volo",
    passengerName: "Nome passeggero",
    vehicleType: "Tipo veicolo",
    paymentType: "Tipo pagamento",
    sendToWhatsApp: "Invia su WhatsApp",
    luxuryService: "Servizio Autista di Lusso",
    flightTracking: "Tracciamento volo",
    doorToDoor: "Servizio Porta a Porta",
    learnMore: "Scopri di più",
  },
  ES: {
    // Navigation
    home: "Inicio",
    cities: "Ciudades",
    fleet: "Flota",
    about: "Nosotros",
    contact: "Contacto",
    services: "Servicios",
    login: "Iniciar sesión",
    logout: "Cerrar sesión",
    myAccount: "Mi cuenta",
    bookNow: "Reservar",
    
    // Hero Section
    heroTitle: "Servicios de Traslado Premium",
    heroSubtitle: "La mejor compañía de traslados desde el aeropuerto. Experimenta el viaje de lujo con nuestro servicio de chófer profesional. Transporte fiable, cómodo y elegante para cada viaje.",
    bookYourTransfer: "Reserva tu traslado",
    callNow: "Llamar ahora",
    service247: "Servicio 24/7",
    professionalDrivers: "Conductores profesionales",
    luxuryFleet: "Flota de lujo",
    
    // Features Section
    whyChooseUs: "Por qué elegirnos",
    experienceTheDifference: "Experimenta la diferencia con nuestro servicio de traslado premium",
    safeSecure: "Seguro y protegido",
    safeSecureDesc: "Vehículos totalmente autorizados y asegurados con conductores profesionales verificados",
    availability247: "Disponibilidad 24/7",
    availability247Desc: "Servicio las 24 horas para llegadas y salidas en cualquier momento",
    premiumFleet: "Flota Premium",
    premiumFleetDesc: "Vehículos modernos y cómodos mantenidos con los más altos estándares",
    support247: "Soporte 24/7",
    support247Desc: "Equipo de atención al cliente dedicado disponible cuando lo necesites",
    
    // Destinations Section
    topDestinations: "Destinos Principales",
    topDestinationsDesc: "Descubre nuestras rutas más populares con conductores profesionales y vehículos de lujo",
    istanbulHotels: "Estambul ⇄ Hoteles",
    istanbulDesc: "Traslado VIP privado desde el aeropuerto con servicio de chófer profesional a todos los hoteles de Estambul.",
    antalyaResorts: "Antalya ⇄ Resorts",
    antalyaDesc: "Traslado de lujo a Lara, Belek, Kemer, Side y todos los principales destinos turísticos.",
    bodrumCity: "Bodrum ⇄ Traslado ciudad",
    bodrumDesc: "Servicio premium a la península de Bodrum, Turgutreis, Gümbet y alrededores.",
    cappadociaTours: "Tours en Capadocia",
    cappadociaDesc: "Traslados exclusivos y servicios de tour por la mágica región de Capadocia.",
    
    // Services Page
    servicesTitle: "Servicios VIP de Aeropuerto y Chófer Premium",
    servicesSubtitle: "Traslados de lujo a los mejores destinos de Turquía",
    servicesMainTitle: "Servicios de Traslado VIP en Turquía",
    servicesIntro: "Meet Transfer ofrece traslados de lujo desde el aeropuerto, servicio de chófer privado y transporte VIP en minivan a los aeropuertos y destinos turísticos más importantes de Turquía. Nuestra flota incluye Mercedes Vito, Mercedes Clase V, minibuses VIP y opciones Maybach. Todos los traslados incluyen chóferes profesionales, seguimiento de vuelos, recepción personalizada, agua y soporte 24/7.",
    readyToBook: "¿Listo para reservar tu traslado VIP?",
    contactViaWhatsApp: "Contáctanos vía WhatsApp para reserva instantánea y servicio personalizado. Nuestro equipo está disponible 24/7 para asistirte.",
    
    // About Page
    aboutTitle: "Sobre Meet Transfer",
    aboutSubtitle: "Tu socio de confianza para traslados premium desde el aeropuerto",
    whoWeAre: "Quiénes somos - El servicio líder de traslados desde el aeropuerto en Turquía",
    aboutIntro1: "Meet Transfer es el servicio líder de traslados premium desde el aeropuerto en Turquía, proporcionando transporte de lujo a los destinos turísticos más populares del país. Fundado con la visión de ofrecer a los viajeros un viaje fluido y cómodo, nos hemos convertido en la opción de confianza para viajeros exigentes, familias y ejecutivos de negocios.",
    aboutIntro2: "Nuestro compromiso con la excelencia se refleja en cada aspecto de nuestro servicio – desde nuestra flota Mercedes impecablemente mantenida hasta nuestros conductores profesionales de habla inglesa que reciben una formación rigurosa. Creemos que tu viaje debe ser tan agradable como tu destino.",
    yearsExperience: "Años de experiencia",
    transfersCompleted: "Traslados completados",
    citiesCovered: "Ciudades cubiertas",
    availability: "Disponibilidad",
    whyChooseMeetTransfer: "Por qué elegir Meet Transfer",
    safetyFirst: "Seguridad primero",
    safetyFirstDesc: "Todos nuestros vehículos son revisados regularmente y nuestros conductores están formados profesionalmente.",
    qualityService: "Servicio de calidad",
    qualityServiceDesc: "Nos enorgullecemos de ofrecer un servicio excepcional con atención a cada detalle.",
    punctuality: "Puntualidad",
    punctualityDesc: "Monitorizamos todos los vuelos y aseguramos que tu conductor esté siempre a tiempo.",
    customerFocus: "Enfoque en el cliente",
    customerFocusDesc: "Tu comodidad y satisfacción son nuestras principales prioridades durante tu viaje.",
    citiesWeServe: "Ciudades que servimos en Turquía",
    meetGreetService: "Nuestro servicio VIP Meet & Greet",
    meetGreetDesc: "Cada traslado desde el aeropuerto incluye nuestro servicio distintivo Meet & Greet. Tu conductor te esperará en la sala de llegadas con un cartel personalizado. Monitorizamos tu vuelo en tiempo real, así que incluso si hay retrasos, tu conductor estará allí cuando aterrices. Sin esperas, sin búsquedas – solo una cálida bienvenida y ayuda con tu equipaje.",
    ourMission: "Nuestra misión es proporcionar a cada huésped una experiencia de viaje que supere las expectativas. Desde el momento de la reserva hasta llegar a tu destino, estamos comprometidos con tu comodidad y seguridad.",
    generalManager: "Director General",
    readyToExperience: "¿Listo para experimentar la diferencia?",
    
    // Contact Page
    contactTitle: "Contáctanos",
    contactSubtitle: "Estamos aquí para ti 24/7",
    contactMainTitle: "Contactar Meet Transfer - Oficinas globales",
    servingWorldwide: "Te servimos desde múltiples ubicaciones en todo el mundo con soporte 24/7",
    fastestWay: "La forma más rápida de contactarnos",
    instantResponses: "Obtén respuestas instantáneas vía WhatsApp para tu reserva de traslado",
    sendMessage: "Envíanos un mensaje",
    yourName: "Tu nombre",
    howCanWeHelp: "¿Cómo podemos ayudarte?",
    sending: "Enviando...",
    messageSent: "¡Mensaje enviado con éxito! Te contactaremos pronto.",
    
    // Fleet Page
    fleetTitle: "Nuestra flota de lujo",
    fleetSubtitle: "Vehículos Mercedes premium para cada ocasión",
    fleetMainTitle: "Flota de traslados VIP Mercedes",
    fleetIntro: "Nuestra cuidadosamente seleccionada flota Mercedes garantiza viajes con el máximo confort y estilo. Desde traslados eficientes desde el aeropuerto hasta servicio de chófer de lujo, tenemos el vehículo perfecto para cada ocasión. Todos los vehículos son regularmente revisados y limpiados según los más altos estándares.",
    needHelp: "¿Necesitas ayuda para elegir?",
    contactForHelp: "Contáctanos y te ayudaremos a elegir el vehículo perfecto para tu traslado",
    
    // Services List
    istanbulService: "Traslado Aeropuerto Estambul (IST y SAW)",
    istanbulFeature1: "Traslados VIP Aeropuerto → Hotel",
    istanbulFeature2: "Taksim, Sultanahmet, Puerto cruceros Galataport",
    istanbulFeature3: "Servicio Chófer de Negocios",
    istanbulFeature4: "Mercedes Vito y Minivans VIP Clase V",
    istanbulFeature5: "Servicio 24/7 + Seguimiento vuelo + Recepción",
    antalyaService: "Traslado Aeropuerto Antalya (AYT)",
    antalyaFeature1: "Lara, Kundu, Belek, Side, Alanya, Kaş, Kemer",
    antalyaFeature2: "Traslados Hoteles de Golf",
    antalyaFeature3: "Opciones Minibús Familia y Grupo",
    antalyaFeature4: "Traslados Resort y Villa",
    bodrumService: "Traslado Aeropuerto Bodrum (BJV)",
    bodrumFeature1: "Yalıkavak Marina, Türkbükü, Gündoğan, Torba",
    bodrumFeature2: "Traslados Villa y Hotel de Lujo",
    bodrumFeature3: "VIP Mercedes Vito, Clase V y Minibús",
    dalamanService: "Traslado Aeropuerto Dalaman (DLM)",
    dalamanFeature1: "Fethiye, Ölüdeniz, Göcek Marina, Marmaris",
    dalamanFeature2: "Traslados Yate + Traslados Villa",
    dalamanFeature3: "Servicio Chófer Privado 24/7",
    izmirService: "Traslado Aeropuerto Izmir (ADB)",
    izmirFeature1: "Éfeso, Çeşme, Alaçatı, Kusadasi",
    izmirFeature2: "Traslados Hotel, Resort y Puerto cruceros",
    cappadociaService: "Traslado Aeropuerto Capadocia (NAV y ASR)",
    cappadociaFeature1: "Göreme, Ürgüp, Avanos, Uçhisar",
    cappadociaFeature2: "Hoteles cueva y Traslados Tour Globo",
    cappadociaFeature3: "Chófer privado VIP para tours",
    
    // Vehicles
    vitoVipName: "Mercedes Vito VIP",
    vitoVipDesc: "Nuestra opción más popular para traslados desde el aeropuerto. El Mercedes Vito VIP ofrece asientos espaciosos, amplio espacio para equipaje y características de confort premium, perfecto para familias y grupos pequeños.",
    vitoName: "Mercedes Vito",
    vitoDesc: "El Mercedes Vito - vehículos de traslado familiar cómodos con el mejor presupuesto.",
    maybachName: "Mercedes Maybach",
    maybachDesc: "La cima del lujo automotriz. Nuestro Maybach ofrece asientos traseros ejecutivos y el viaje más suave para huéspedes VIP y ejecutivos.",
    sprinterName: "Mercedes Sprinter VIP Minibús",
    sprinterDesc: "Perfecto para grupos más grandes, nuestro Sprinter VIP ofrece asientos estilo avión para hasta 16 pasajeros con pantallas individuales y comodidades premium.",
    
    // Destinations Page
    destinationsTitle: "Destinos VIP en Turquía",
    destinationsSubtitle: "Traslados Premium desde el Aeropuerto y Servicios de Chófer Privado",
    destinationsMainTitle: "Destinos de Traslado desde el Aeropuerto en Turquía",
    destinationsIntro: "Descubre los mejores destinos que servimos en Turquía. Desde marinas de lujo hasta centros históricos, Meet Transfer ofrece traslados premium desde el aeropuerto, chóferes privados y servicio VIP de minivan en cada región principal.",
    keyLocations: "Ubicaciones clave",
    more: "más",
    bookTransfer: "Reservar",
    transfer: "Traslado",
    premiumVipFleet: "Flota VIP Premium Disponible",
    premiumVipFleetDesc: "Todos los destinos cuentan con nuestros vehículos de lujo Mercedes Vito, Clase V, Minibús VIP y Maybach con chóferes profesionales, seguimiento de vuelos y soporte 24/7.",
    bookViaWhatsApp: "Reservar vía WhatsApp",
    cityAirportTransfers: "Traslados Ciudad y Aeropuerto",
    resortDestinations: "Destinos Resort",
    luxuryMarinas: "Marinas de Lujo",
    coastalAreas: "Zonas Costeras",
    aegeanCoast: "Costa Egea",
    caveHotelsBalloon: "Hoteles Cueva y Zonas de Globos",
    
    // Common
    passengers: "Pasajeros",
    luggage: "Equipaje",
    from: "Desde",
    to: "Hasta",
    price: "Precio",
    name: "Nombre",
    email: "Correo",
    phone: "Teléfono",
    message: "Mensaje",
    send: "Enviar",
    whatsappBooking: "Reservar en WhatsApp",
    meetGreet: "Servicio Meet & Greet",
    vipTransfer: "Traslado VIP Aeropuerto",
    ourFleet: "Nuestra Flota",
    destinations: "Destinos",
    reviews: "Reseñas",
    priceList: "Lista de precios",
    faq: "FAQ",
    aboutUs: "Sobre nosotros",
    contactUs: "Contáctenos",
    termsConditions: "Términos y Condiciones",
    selectAirport: "Seleccionar aeropuerto",
    selectDestination: "Seleccionar destino",
    dateTime: "Fecha y hora",
    flightNumber: "Número de vuelo",
    passengerName: "Nombre del pasajero",
    vehicleType: "Tipo de vehículo",
    paymentType: "Tipo de pago",
    sendToWhatsApp: "Enviar a WhatsApp",
    luxuryService: "Servicio de Chófer de Lujo",
    flightTracking: "Seguimiento de vuelo",
    doorToDoor: "Servicio Puerta a Puerta",
    learnMore: "Más información",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const getLanguageFromPath = (pathname: string): Language => {
  const pathParts = pathname.split("/").filter(Boolean);
  const firstPart = pathParts[0]?.toLowerCase();
  
  if (firstPart && LANGUAGE_PREFIXES[firstPart]) {
    return LANGUAGE_PREFIXES[firstPart];
  }
  
  return "EN";
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const location = useLocation();
  const language = getLanguageFromPath(location.pathname);

  const t = (key: string): string => {
    return translations[language][key] || translations["EN"][key] || key;
  };

  const getLocalizedPath = (path: string): string => {
    const prefix = LANGUAGE_TO_PREFIX[language];
    const normalizedPath = path.startsWith("/") ? path : `/${path}`;
    
    if (language === "EN") {
      return normalizedPath;
    }
    
    return `${prefix}${normalizedPath === "/" ? "" : normalizedPath}`;
  };

  const setLanguage = () => {};

  useEffect(() => {
    document.documentElement.lang = language.toLowerCase();
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getLocalizedPath }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
