// This file is auto-generated by Lovable. Do not modify it.

import { supabase } from "../supabase/client";

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
      const { data, error } = await supabase.auth.signInWithOAuth({
        provider,
        options: {
          redirectTo: opts?.redirect_uri,
          queryParams: opts?.extraParams,
          skipBrowserRedirect: true,
        },
      });

      if (error) {
        return { error };
      }

      if (data.url) {
        window.location.href = data.url;
        return { redirected: true };
      }

      return { error: new Error("No redirect URL returned") };
    },
  },
};
