// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabaseStorage } from '@/lib/supabaseStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Supabase environment variables are missing. Please check your .env configuration.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// iOS Safari uyumlu hibrit storage (localStorage + sessionStorage fallback).
// SameSite: Token'lar localStorage'da tutulur; Supabase sunucu çerezleri kendi domain'inde.
// Oturum kalıcılığı için persistSession + autoRefreshToken etkin.
// Fallback to empty strings to prevent crash on initialization if env vars are missing
export const supabase = createClient<Database>(
  SUPABASE_URL || "https://missing-url.supabase.co", 
  SUPABASE_PUBLISHABLE_KEY || "missing-key", 
  {
  auth: {
    storage: supabaseStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});